pipeline{
    
    agent any

    stages{
        stage("build"){
            steps{
                echo "building the application..."
            }
        }
    }

    stages{
        stage("test"){
            steps{
                echo "testing the application..."
            }
        }
    }

    stages{
        stage("deploying"){
            steps{
                echo "deploying the application..."
            }
        }
    }
}